"""Paleta visual centralizada com temas locais e materiais discretos."""

from __future__ import annotations

THEME_OPTIONS = (
    ("light", "Claro", "Leve e neutro"),
    ("dark", "Escuro", "Confortável em ambientes com pouca luz"),
    ("graphite", "Grafite", "Escuro neutro com menos saturação"),
    ("ocean", "Oceano", "Azul profundo com destaque técnico"),
)
THEME_KEYS = {item[0] for item in THEME_OPTIONS}


class AppColors:
    """Cores semânticas atualizadas antes de cada reconstrução da interface."""

    PRIMARY = "#087E8B"
    PRIMARY_LIGHT = "#D5F6F7"
    PAGE_BACKGROUND = "#EEF4F8"
    NAV_BACKGROUND = "#FDFEFE"
    NAV_SELECTED = "#DCF6F7"
    NAV_HOVER = "#EDF7F9"
    NAV_TEXT = "#475569"
    SURFACE = "#FFFFFF"
    TEXT_PRIMARY = "#0F172A"
    TEXT_SECONDARY = "#64748B"
    DIVIDER = "#DCE6ED"
    WARNING = "#D97706"
    WARNING_LIGHT = "#FEF3C7"
    DANGER = "#DC2626"
    DANGER_LIGHT = "#FEE2E2"
    INFO = "#2563EB"
    INFO_LIGHT = "#DBEAFE"
    DRYING = "#7C3AED"
    DRYING_LIGHT = "#EDE9FE"
    WHITE = "#FFFFFF"
    GLASS_SURFACE = "#EFFFFFFF"
    GLASS_SURFACE_ACCENT = "#E8F7FBFC"
    GLASS_BORDER = "#99D5E2E8"
    SURFACE_SHADOW = "#190F172A"
    INTERACTIVE_HOVER = "#16087E8B"
    INTERACTIVE_PRESSED = "#26087E8B"
    ACCENT_GLOW = "#3606B6C2"

    @classmethod
    def normalize_mode(cls, mode: str | None) -> str:
        normalized = (mode or "light").strip().casefold()
        return normalized if normalized in THEME_KEYS else "light"

    @classmethod
    def apply_mode(cls, mode: str) -> None:
        """Aplica uma paleta completa mantendo contraste e hierarquia previsíveis."""

        mode = cls.normalize_mode(mode)
        if mode == "dark":
            cls.PRIMARY = "#42D7C8"
            cls.PRIMARY_LIGHT = "#123F42"
            cls.PAGE_BACKGROUND = "#0C1420"
            cls.NAV_BACKGROUND = "#111C2A"
            cls.NAV_SELECTED = "#153D42"
            cls.NAV_HOVER = "#172737"
            cls.NAV_TEXT = "#C8D4E0"
            cls.SURFACE = "#162334"
            cls.TEXT_PRIMARY = "#F7FAFC"
            cls.TEXT_SECONDARY = "#9EB0C2"
            cls.DIVIDER = "#2B3C4D"
            cls.WARNING = "#FBBF24"
            cls.WARNING_LIGHT = "#433516"
            cls.DANGER = "#FB7185"
            cls.DANGER_LIGHT = "#44202A"
            cls.INFO = "#67A9FF"
            cls.INFO_LIGHT = "#183555"
            cls.DRYING = "#C4B5FD"
            cls.DRYING_LIGHT = "#312B50"
            cls.WHITE = "#FFFFFF"
            cls.GLASS_SURFACE = "#E619293A"
            cls.GLASS_SURFACE_ACCENT = "#E51B343D"
            cls.GLASS_BORDER = "#70445A68"
            cls.SURFACE_SHADOW = "#52000000"
            cls.INTERACTIVE_HOVER = "#2042D7C8"
            cls.INTERACTIVE_PRESSED = "#3542D7C8"
            cls.ACCENT_GLOW = "#5042D7C8"
            return
        if mode == "graphite":
            cls.PRIMARY = "#67D6D0"
            cls.PRIMARY_LIGHT = "#24373A"
            cls.PAGE_BACKGROUND = "#171A1F"
            cls.NAV_BACKGROUND = "#1D2026"
            cls.NAV_SELECTED = "#26373A"
            cls.NAV_HOVER = "#282C33"
            cls.NAV_TEXT = "#D1D5DB"
            cls.SURFACE = "#22262D"
            cls.TEXT_PRIMARY = "#F3F4F6"
            cls.TEXT_SECONDARY = "#A7AFBA"
            cls.DIVIDER = "#353B44"
            cls.WARNING = "#F0B84B"
            cls.WARNING_LIGHT = "#453A20"
            cls.DANGER = "#F27B83"
            cls.DANGER_LIGHT = "#47282B"
            cls.INFO = "#7DA8E8"
            cls.INFO_LIGHT = "#29384D"
            cls.DRYING = "#B7A7E8"
            cls.DRYING_LIGHT = "#383246"
            cls.WHITE = "#FFFFFF"
            cls.GLASS_SURFACE = "#E62A2E35"
            cls.GLASS_SURFACE_ACCENT = "#E62D3839"
            cls.GLASS_BORDER = "#6B50565F"
            cls.SURFACE_SHADOW = "#50000000"
            cls.INTERACTIVE_HOVER = "#2467D6D0"
            cls.INTERACTIVE_PRESSED = "#3867D6D0"
            cls.ACCENT_GLOW = "#4D67D6D0"
            return
        if mode == "ocean":
            cls.PRIMARY = "#5AD7E8"
            cls.PRIMARY_LIGHT = "#17384C"
            cls.PAGE_BACKGROUND = "#071724"
            cls.NAV_BACKGROUND = "#0C2132"
            cls.NAV_SELECTED = "#113B51"
            cls.NAV_HOVER = "#123047"
            cls.NAV_TEXT = "#C6D9E8"
            cls.SURFACE = "#0F2638"
            cls.TEXT_PRIMARY = "#F3FAFD"
            cls.TEXT_SECONDARY = "#98B5C8"
            cls.DIVIDER = "#234156"
            cls.WARNING = "#F6C45C"
            cls.WARNING_LIGHT = "#40351E"
            cls.DANGER = "#FF7F8A"
            cls.DANGER_LIGHT = "#49252D"
            cls.INFO = "#78B9FF"
            cls.INFO_LIGHT = "#173C5C"
            cls.DRYING = "#C2B4FF"
            cls.DRYING_LIGHT = "#332F57"
            cls.WHITE = "#FFFFFF"
            cls.GLASS_SURFACE = "#E5102A3D"
            cls.GLASS_SURFACE_ACCENT = "#E5153448"
            cls.GLASS_BORDER = "#70496A7C"
            cls.SURFACE_SHADOW = "#59000000"
            cls.INTERACTIVE_HOVER = "#245AD7E8"
            cls.INTERACTIVE_PRESSED = "#3A5AD7E8"
            cls.ACCENT_GLOW = "#4F5AD7E8"
            return

        cls.PRIMARY = "#087E8B"
        cls.PRIMARY_LIGHT = "#D5F6F7"
        cls.PAGE_BACKGROUND = "#EEF4F8"
        cls.NAV_BACKGROUND = "#FDFEFE"
        cls.NAV_SELECTED = "#DCF6F7"
        cls.NAV_HOVER = "#EDF7F9"
        cls.NAV_TEXT = "#475569"
        cls.SURFACE = "#FFFFFF"
        cls.TEXT_PRIMARY = "#0F172A"
        cls.TEXT_SECONDARY = "#64748B"
        cls.DIVIDER = "#DCE6ED"
        cls.WARNING = "#D97706"
        cls.WARNING_LIGHT = "#FEF3C7"
        cls.DANGER = "#DC2626"
        cls.DANGER_LIGHT = "#FEE2E2"
        cls.INFO = "#2563EB"
        cls.INFO_LIGHT = "#DBEAFE"
        cls.DRYING = "#7C3AED"
        cls.DRYING_LIGHT = "#EDE9FE"
        cls.WHITE = "#FFFFFF"
        cls.GLASS_SURFACE = "#EFFFFFFF"
        cls.GLASS_SURFACE_ACCENT = "#E8F7FBFC"
        cls.GLASS_BORDER = "#99D5E2E8"
        cls.SURFACE_SHADOW = "#190F172A"
        cls.INTERACTIVE_HOVER = "#16087E8B"
        cls.INTERACTIVE_PRESSED = "#26087E8B"
        cls.ACCENT_GLOW = "#3606B6C2"
